spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Redli9600,.0@
    url: jdbc:mysql://redli.xin:3306/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: redli.xin
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
